### ISSUE TITLE
Unclear queue configuration 

### ISSUE THREAD

**Issue by daviesthomas** [justanhduc/task-spooler#19]
Hey, 

Awesome repo, hugely helpful. 

We are unsure if this is a usage problem, or a bug in task spooler. 

When configuring the queue to work on multiple GPUs we need to run, 
`ts -S 4`
And to set the log directory we need to run, 
`ts --set_logdir logs/`
but when running them together we notice that `-S` is ignored
`ts -S 4 --set_logdir logs/`

Can task spooler options only be set one at a time? If so, we might benefit from some clarity in the readme/guides.

**Comment by justanhduc** [comment]
Hey @daviesthomas. Thanks for using `ts`!
No it's not a bug and yes `ts` can perform only one action at a time. The reason is after parsing the arguments, `ts` does not do it immediately but sets a request flag of what to do. So this flag will be overwritten by later args and in the end, `ts` will perform only the last action. Note that it does not apply to job-queuing options as you can pass as many args as you want.
Thanks for pointing this out. I will make this clear in the readme. If you have any further problem, just let me know.

**Comment by daviesthomas** [comment]
Thanks ! Good to know.
